### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by satirical-muzzle** [0perationPrivacy/VoIP#118]
Android
Vanadium
Telnyx

I was 8 commits behind and updated today. The app's webpage loads briefly, but then receives a 404 error. I have tried clearing browser history / cookies. I do not have issues accessing the VoIP app on desktop.

**Comment by 0perationPrivacy** [comment]
That can happen sometimes due to cache.
- Make sure the URL is only the domain and no URI or directory path in case you're using an older bookmark.
- If you've set a custom directory path, make sure you're entering that in
- Check your env variables
- Try a different browser to test the cache, try incognito mode. The latest code on both the public voip site and github is the same.

**Comment by satirical-muzzle** [comment]
I typed in the pure domain (no https or any forward slashes) and that solved the issue. I've updated my bookmark now. Thank you!
