### ISSUE TITLE
Profile Setting (Telnyx) Error: (Status 400) Invalid URL

### ISSUE THREAD

**Issue by plafer** [0perationPrivacy/VoIP#121]
- **Platform:**  Desktop
- **Browser:** Firefox
- **App Version:** v0.87 (self-hosted)
- **Provider:** Telnyx
- ### Describe the bug
When attempting to connect to my Telnyx phone number using the Telnyx API Key, after clicking "Save", I get a 400 Invalid URL error.

**To Reproduce**
1. Create a new profile
2. Access Profile Settings
3. Add Telnyx API key, click "Get Number", and select number
4. Click Save.
5. See a modal "The call setting is available. Do you want to override the call setting?" - click either options (both have the same behavior). Note that I don't understand what this message is about.
6. See Error modal: (Status 400) Invalid URL

**Expected behavior**
I expect to be able to access my SMS messages for the phone number.

**Comment by 0perationPrivacy** [comment]
> Note that I don't understand what this message is about.

If you have configured Linphone or any other VoIP calling app using that same phone number, VoIP Suite will override that setting and instead use itself for making/receiving voice calls. You can't have 2 destinations. So the prompt is is to ask you if you want to override those settings or keep Linphone for calling and use VoIP Suite only for the SMS part, because it does both, whereas Linphone or other similar apps only provide calling.

But since it is web based calling (browser has to be open), I prefer using another app (Linphone) for calls, until the mobile app for this is ready.

Regarding your error, I cannot reproduce it.

**Comment by plafer** [comment]
Oh, I didn't understand that part, thank you for the explanation! I'll also wait for the mobile app then :)

If ever you find the cycles, I'm sure updating the wiki with what you just explained to me would be valuable to others too.

**Comment by 0perationPrivacy** [comment]
> Oh, I didn't understand that part, thank you for the explanation! I'll also wait for the mobile app then :)
> 
> If ever you find the cycles, I'm sure updating the wiki with what you just explained to me would be valuable to others too.

I update the wiki with these instructions. Thanks.
https://github.com/0perationPrivacy/VoIP/wiki/Web-Application
