### ISSUE TITLE
Cannot start upgraded repo

### ISSUE THREAD

**Issue by timconsidine** [0perationPrivacy/VoIP#131]
- **Platform:**  : self-host in Ubuntu
- **Browser:** n/a
- **App Version:** 0.89
- **Provider:** Telnyx
- ### Describe the bug
I did git clone on the latest repo (0.89)
I copied over the .env from previous working deployment.
I ran `npm install` and then `node app.js &`
I get an error as below :
```
root@together-ibex:~/VoIP# node app.js &
[2] 16489
root@together-ibex:~/VoIP# /root/VoIP/app.js:101
if( process.env.HTTPS.trim() === 'true'){
                      ^

TypeError: Cannot read property 'trim' of undefined
    at Object.<anonymous> (/root/VoIP/app.js:101:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**To Reproduce**
As above
NB : direct deployment of repo in Ubuntu, not using Heroku

**Expected behavior**
App to start

**Comment by timconsidine** [comment]
Oooops my error
The format of .env has changed with additional declaration of HTTPS
Copying across my previous .env missed this
Add the `HTTPS = false` line and it is working

I don't understand why HTTPS is set to false
Maybe it doesn't matter, as my nginx sets it to 443

**Comment by 0perationPrivacy** [comment]
> Oooops my error The format of .env has changed with additional declaration of HTTPS Copying across my previous .env missed this Add the `HTTPS = false` line and it is working
> 
> I don't understand why HTTPS is set to false Maybe it doesn't matter, as my nginx sets it to 443

As per the wiki:


HTTPS | default is false (for local testing without a certificate). Change it to true to force the page to redirect to https
-- | --

Even if you don't change it and leave it at http, either your **web server** can force the redirect or your **WAF** (cloudflare, etc). But local access (for testing) will break because you can't issue a valid certificate on localhost.

All environment variables must be set, that's why I've provided a default file with some default values in it. They can all be overridden at runtime, they're just there for fallback in case you forget to set them.

Glad you got it to work 👍🏻
