### ISSUE TITLE
Can send but can't receive messages

### ISSUE THREAD

**Issue by zmoynihan** [0perationPrivacy/VoIP#16]
**Platform:** [Desktop or Mobile]
**Browser:** [Firefox, Safari]
**App Version:** [v0.60-beta]
**Provider:** [Telnyx]
### Describe the bug
I can send messages but cannot receive. Telnyx shows messages were received. My Telnyx account is also funded.

Also, nothing happens when I click the phone icon. 

**To Reproduce**
1. Go to external phone message account. Reply to message sent from this app.

**Expected behavior**
Receiving text message from outside number.

<<Sorry for the series of bug requests>>

**Comment by 0perationPrivacy** [comment]
just make sure ur BASE_URL is correct in the environment variables in heroku, that's what defines the webhooks to receive messages.

**Comment by PavelNL** [comment]
Could you try to send a message from the phone to the Telnyx number without doing a Reply?

Then Telnyx has a WebHook tab in Debugging section, where you could see all their event logs. While doing an operation (like sending SMS), kindly check that page (refresh might be required) for eventual info.

PS: I'm using US and UK numbers in Telnyx and had no issues while was testing today.

**Comment by randomlikelihood** [comment]
> just make sure ur BASE_URL is correct in the environment variables in heroku, that's what defines the webhooks to receive messages.

One thing you can check as well is whether the BASE_URL entered has a forward slash at the end—i.e., https://your-app-name.herokuapp.com/ versus https://your-app-name.herokuapp.com.

**Comment by t4jqczs4agzp57xvqfs7** [comment]
I just figured out the hard way that my base URL did not have the / at the end, so I updated the value to have / at the end. I even restarted the dynos on heroku, and rebuilt the app, - this did not fix the issue - UNTIL I deleted the profiles in the VoIP app that i created, and made them over again.

That is because when you create the profile, it saves the incorrect configuration. Try recreating the profiles to see if that helps after you add the / to your base url config.
 
Once I referenced this file it all made sense:
https://github.com/0perationPrivacy/VoIP/blob/main/app/controller/setting.controller.js

@PRPSDev

**Comment by zmoynihan** [comment]
That was it!  Bravo!!!

**Comment by 0perationPrivacy** [comment]
will adding protection for a leading `https://` and trailing `/` in the next update.

**Comment by PRPSDev** [comment]
@t4jqczs4agzp57xvqfs7 OK! Now we're talking. Er, texting. That was the missing link in my issue. THANK YOU.

Also found another annoying little hangover from a different attempt at getting VOIP messaging to work: "Texting" from Signal. Oops. Turns out, if you use Signal for "messaging" (which, you know, I do), it goes through Signal's servers (who knew? ;-) ) instead of Twilio's. I forgot to switch to "Messages" app when testing it tonight and spent 5-10 minutes trying to figure out why now I could text back and forth between two VOIP numbers _in the app_ but a real phone outside the app couldn't get a message through.
