### ISSUE TITLE
Meaning/implication of error message "Error - Number already assigned to another profile!"

### ISSUE THREAD

**Issue by VisitorSnowdrop** [0perationPrivacy/VoIP#164]
- **Platform:**  Laptop/PopOS
- **Browser:** Firefox
- **App Version:** [e.g v0.x] v0.89
- **Provider:** Twilio
- I'm unsure about the above error message.  All worked perfectly on Heroku, but now switching to Render.  Followed directions > entered Twilio SID and token > chose my first number > was asked if I wanted to keep or override my call setting (I said keep) > pressed Save.  That's when the error message appears.  I tried deleting the VoIPSuite Profile and starting over, but that didn't help.  I then went into Twilio and edited out the messaging webhooks that mentioned the old Heroku path, but that didn't help.  (I didn't delete/change anything on Heroku - I'd have tried that but Heroku won't let me into my account for some reason.)  SO, I'm hoping for clarification on where the Error Message is trying to point me to with respect to the "other profile."  

**To Reproduce**
1. Set up Twilio account and phone number, then get app working on Heroku
2. Set up alternative app on Render and try configuring the Twilio number that previously worked on Heroku app
3. See error

**Expected behavior**
A successful Save with no error message.

**Comment by VisitorSnowdrop** [comment]
Since leaving my previous message, I was able to get into my Heroku account and deleted that VoIPSuite app (though for now I kept my Heroku user account).  Unfortunately this didn't change the described behavior for my Render VoIP Suite app.  I still don't understand what "existing profile" the error message can be referring to.  Any clarification or suggestions would be appreciated.

**Comment by VisitorSnowdrop** [comment]
It appears that the existing profile conflict probably is on my MongoDB.  I had been using the same MongoDB for Render as I had used for Heroku.  (Once I linked Render to a brand new MongoDB account, I was able to proceed without the error message.)  So, my suggestion is to enhance the error message that currently says "Error - Number already assigned to another profile!" to say instead "Error - Number already assigned to another profile **in MongoDB**!".  (As a side note, with the new Mongo account, I've been able to link VoIPSuite to my Twilio numbers and send texts, but I'm still troubleshooting an inability to receive texts....  )

**Comment by 0perationPrivacy** [comment]
Hi,
I don't believe that error is related to MongoDB because I have more than 2 instances of VoIP suite running on Heroku and Render all pointing to the SAME mongodb database. You can easily have 2 instances running and configure the backup instance in the failover section so Twilio sends the message to the failover instance IF the primary one fails.

If another VoIP Suite profile is configure with that number, it will give that error. You must delete that profile, un-assign it from it, or delete the entries in Twilio for it to go away. It's sort of a safety feature if you accidentally try to assign the same phone number to  a second profile, you don't steal the number away from the first profile. Linking a new mongodb instance essentially does that, forgets any profile information.

As the app matures, we will try to put in more detailed information in the error messages. Right now, as will all errors, it could mean many things, so usually details are not provided beyond the error message.
