### ISSUE TITLE
Receiving SMS

### ISSUE THREAD

**Issue by jcon-5** [0perationPrivacy/VoIP#166]
- **Platform:**  Desktop 
- **Browser:** Firefox
- **App Version:**  v0.89
- **Provider:** Twilio

I'm also currently having issues receiving text messages through the app. I upgraded and funded my Twilio account a while back, verified my phone number, and believe I fixed any slash issues I've seen in previous threads. What additional recommendations if any are there to fix this. Thank you!

**Comment by 0perationPrivacy** [comment]
make sure there's nothing in twilios number settings that's limiting sms's to only certain countries. US to US is the default, so you should not have any issues there. Once your account is verified, then you should be able to send sms's anywhere.

**Comment by vfnilernwreg** [comment]
Hello all, I am also having this issue. I am able to send sms from twillio number without issue but I cannot recive sms at the same number(s).  My twilio account is also active/verified and everything was working fine until I switched to Render from Heroku.

I setup the app again from scratch using the updated instructions](https://inteltechniques.com/voip.suite.html) rather than just switching from Heroku to avoid any databse conflicts.

Under "active numbers" in "console" I can see that the app made the "webhook to POST" for the number in question as "<your voipsuite instance base url>.comapi/setting/receive-sms/twilio". The messages should be coming in but yet they do not?
Is there an extra step that I overlooked or maybe something is different now with render or with twilio?
Where would we look in the settings if this is the case?

**Comment by 0perationPrivacy** [comment]
> Hello all, I am also having this issue. I am able to send sms from twillio number without issue but I cannot recive sms at the same number(s). My twilio account is also active/verified and everything was working fine until I switched to Render from Heroku.
> 
> I setup the app again from scratch using the updated instructions](https://inteltechniques.com/voip.suite.html) rather than just switching from Heroku to avoid any databse conflicts.
> 
> Under "active numbers" in "console" I can see that the app made the "webhook to POST" for the number in question as "BASE_URL.comapi/setting/receive-sms/twilio". The messages should be coming in but yet they do not? Is there an extra step that I overlooked or maybe something is different now with render or with twilio? Where would we look in the settings if this is the case?

@vfnilernwreg your issue I can see is the leading slash. BASE_URL should have a forward slash after it.
Once you edit that (in the environment variable in Render), go to your VoIP Suite app and hit the `save` button under your twilio profile settings. That will push the settings again and you should see a slash (like .com/api ) in the twilio webhook.
