### ISSUE TITLE
Creating a Dockerfile

### ISSUE THREAD

**Issue by Farrahs-Cloud-Art** [0perationPrivacy/VoIP#18]
Hello 0perationPrivacy.
On my fork, I'm making a Dockerfile for this application. (I just like to maintain all my servers in containers)
I am not familiar with nodejs, though, so would you mind if I asked you questions here to help containerize this and possibly give you a merge request, later?

If not, feel free to close this issue.

**Comment by 0perationPrivacy** [comment]
Sure, I'm not familiar with docker files. So it will be an education process for me as well. We can take this offline as a side project. The purpose of keeping the code open in Node was to sync it with Heroku (or any other PaaS) and a db to make it easy and free to self host. Minimize the learning and deployment process for the common user.

**Comment by Farrahs-Cloud-Art** [comment]
I understand it would be more than is intended.
Making a containerized setup would be more for people wanting to self host this, like me.
How would you want to communicate offline?
If email works, you could send me an email farrah (at) cloudart dot moe.

**Comment by selfroasted** [comment]
> ontainerized setup would be more for people wanting to self host this, like me.
> How would you want to communicate offline?

If you end up doing anything with the Dockerfile, let me know. I'd love to be smart enough to containerize this on my own!

**Comment by privacyosint** [comment]
If we do decide this, we will see it the closed list

**Comment by Farrahs-Cloud-Art** [comment]
> > ontainerized setup would be more for people wanting to self host this, like me.
> > How would you want to communicate offline?
> 
> If you end up doing anything with the Dockerfile, let me know. I'd love to be smart enough to containerize this on my own!

Making the dockerfile is easy, actually. Already made it on my fork: https://github.com/Farrahs-Cloud-Art/Containerized_VoIP
Integrating it with mongo and knowing what needs to be done on the node side is the hard part, but just because I have not worked with a nodeJS server before.

**Comment by timconsidine** [comment]
> > > ontainerized setup would be more for people wanting to self host this, like me.
Like me !
It's fine to have privacy tools, but then to place them on public mongo and heroku seems wrong to me.
Understand the thinking and the logic.
But much better to have a good-self-host option.

>  Once the "self hosted" option is documented, I'll be able to finish it easily.

What do you consider the status of your Dockerfile package ?

**Comment by CloudArtAdmins** [comment]
The dockerfile itself works, as far as I can tell.
Just connecting it to mongo-db and such is what I'm not currently familiar with.

**Comment by timconsidine** [comment]
> The dockerfile itself works, as far as I can tell. Just connecting it to mongo-db and such is what I'm not currently familiar with.

I think the connection to db is frequently  setup by creating a docker-compose.yml with a db service specified.
How the underling app code needs to change to support this, I am not sure.
I can't see easily the db connection the app.

**Comment by timconsidine** [comment]
I'm not sure why this app needs such a heavy-weight db as Mongo.
sql-lite should be sufficient and much more easily integrated.

The repo https://github.com/pawelmalak/flame might give some clues on how to package this app with a db 

Sorry, my docker skills are just in deploying, not in creating

**Comment by 0perationPrivacy** [comment]
Mongodb is not only light weight, it is way more secure. Look at the [OWASP Top 10](https://owasp.org/Top10/), SQL injection attacks have always been in the top-3 for over a decade. MongoDB is a NOSQL database, sure there's a possibility of a NOSQL attack, but it's so low that it doesn't even make the cut in the OWASP list. And for such an attack you need to modify code, host it and have someone use it. In existing self-hosted compilations of running code, this vulnerability is EXTREMELY low.

Mongodb is also LESS complex than SQL, more scalable and easier to install and get running in no time. No creating tables beforehand, no complex joins or lookup queries, no defining ANY structure.
If I want to add a new field, i simply add it in the object without affecting any "tables" and without re-indexing and creating another row in a table and potentially breaking and redoing the whole application.

Imagine a table with a million rows, then you add just one more column, you just added a field to a million rows. In mongodb, you only add a field to whichever document requires it, saves a lot of space, and complexity and less disruptive to structure.

When first developing this app, I had mongodb running on localhost. With almost zero knowledge of mongodb when I started, it took me 5 mins to get up and running.

The code doesn't need any modifications if you change the location of the db from cloud to local, just change the environment variable and point it to localhost, which is the default anyways.

The reason I prefer a cloud based db is the MAJORITY of users want it to be easy and quick to set up. With mongodb.com, you don't worry about databases setup, backup, uptime, etc. With self hosted db, if anything goes wrong, there's a lot of troubleshooting for the average tech user and very hard to help out in a forum. That being said, it will work, I just don't have the time to test it. Feel free to document the steps.

With Heroku, it's also easy to host it (I chose it because it's popular and has a free tier, you could replicate it with any other PaaS provider). Self hosting on a VPS or your own server requires additional knowledge of firewalls, NAT,  ports, linux commands, DNS entries, etc as you are responsible for configuring the "infrastructure" (vs the PaaS).

Overall, there are hundreds of ways to do this (just look at all the other messaging apps, signal, wire, element, whatsapp), there's no right or wrong way.

Regarding privacy, this is sms, there's no expectation of privacy anyways. This can never be end-to-end-encrypted, it goes through the carrier. We're just cutting the middle-party, taking some control of our own data and decreasing dependence on them.
(Sorry for the long answer.)

**Comment by vxrx** [comment]
@0perationPrivacy 

if your architecture is secure by design sql or nosql attack surfaces are minimal at best.  but in this case mongodb is a good design choice considering the ease of development and not having to be concerned with strict sql trappings and structure.

i do not disagree that a hosted database or heroku to launch this application is a bad idea, but i do agree with others that having a stack where this can be easily deployed would be valuable for your initiatives, particularly with the homelab and self-hosted crowd.

i believe @CloudArtAdmins has started to make headway on a dockerized version of this application.  i cloned it and it would not build properly as the node modules are not getting picked up which when trying to build raises multiple exceptions related to the modules that the application requires.

i've started work on a docker-compose setup that will allow the application to be dropped onto a single docker host, single or multi-node docker swarm, or kubernetes `where i'm currently testing`.  if you'd like to add this to the project list and it's something your group decides on i can put this together for public consumption.

**Comment by 0perationPrivacy** [comment]
I've test this on a linux machine with local mongodb running, everything builds and runs fine, only then do I change the db parameter string to the cloud version and host it online. There's a front-end and a backend code, you're probably not compiling the front-end and only the backend. It pretty modular and should be easy to host pretty much anywhere, all you need is a node.js environment.
Once I go through all the milestones and app, I will definitely get to an easy packaged way of self hosting the db as well.

Keep in mind, there HAS to be an online cloud component. If your local infrastructure is not available because you host at home, sms delivery is lost. So it's NOT a bad thing to host it in the cloud, it's actually preferred unlike most applications. Especially if you want to sync it in the future between the web version and the app.
And with other online features coming up soon (email and voip calling) it will be a pain in the b*tt to open ports and allow syncing between email, voip, sms, mms storage, db, web app, apk, etc if it's all locally hosted. You can't host all those things and maintain them locally, not for the masses at least. BUT the option is there, there's nothing restricting in the code to allow that, in fact, everything is actually tested locally first.

**Comment by timconsidine** [comment]
Self-hosting is not exactly and always the same as local hosting.
If I self-host this app, I would put it in on a VPS 'in the cloud' with a local mongo db on the VPS.
Putting the app and mongo in a docker deployment would cut Bazzell's 1 hour install process to 15 mins, and eliminate a lot of support & maintenance issues.

**Comment by vxrx** [comment]
@timconsidine in my proof of concept i have mongo and node dockerized and traefik is the reverse proxy which handles ingress and routing.  so far it works fine minus some of the node module inclusion within the dockerfile.

lxc is an option, but i'm not sure most users are going to be using lxc and many have significantly more domain knowledge of docker vs lxc.  we can do both and provide multiple deployment methodologies.

**Comment by 0perationPrivacy** [comment]
@timconsidine 
check this out:
https://docs.mongodb.com/manual/reference/connection-string/#examples-1

`mongodb://username:password@localhost/dbname`

**Comment by CloudArtAdmins** [comment]
> > Doesn't LXC stand for Linux Containers? So it is meant for Linux, thus should run well on there.
> > > I realise this may not help much with getting a Docker install going, but at least it can be one form of containerisation for self-hosters.
> > 
> > 
> > No worries, here, having some kind of base to work from is usually all I need to convert setup documents to podman/docker.
> 
> I want to test this out too once you have it running @CloudArtAdmins

Having someone, who isn't me, to test too is always nice to have. So that would be appreciated, thank you.
I'll @ you when I can say it is go-for-testing.

**Comment by timconsidine** [comment]
> Yes, the application will wait for the `status` of the message, whether it failed, succeeded, etc. And if the inbound webhook is not being allowed, it will not know the status. In reality this is 2 way communication (VoIP) unlike regular sms.

All working now, inbound and outbound !
Thanks again @0perationPrivacy 
I will write up my notes and post a link

**Comment by timconsidine** [comment]
>  Just to clarify you did not go forward with setting up a heroku or mongodb stack using their online resources? 

No I did not touch heroku or mongodb.com

> I wonder when I get to the step where I have to connect the telnyx API if there will be any issues since its already been deployed/connected to heroku and mongodb? We'll find out soon. Ill report any issues.

I'm not sure, but I think you can just change the message profile webhook in Telnyx.
The app doesn't know about prior Telnyx config and Telnyx just needs to know where to sned it from now.
I have changed Telnyx webhook value without a problem previously.

**Comment by 0perationPrivacy** [comment]
@timconsidine You do NOT need to create a messaging profile in Telnyx (or Twilio). The app creates it for you when you put in the API key and hit save. That's what the code is doing in the backend, doing all config for you and pulling the number in the dropdown.
Should save you a few steps.

**Comment by timconsidine** [comment]
> You do NOT need to create a messaging profile in Telnyx (or Twilio). 

That's brilliant ... but how does Telnyx know what webhook to use ?  
Or you're saying that it is set up by the app ?  Awesome !!
I will update my document.

If I have set up the messge profile, does it break the app ?
Or otherwise not advided ?
Seems to be working ! 🤞

**Comment by timconsidine** [comment]
> Ive continued down the prompts with LXD. Hopefully this will be helpful to others trying this... let me know if any of the peramiters I selected should be changed

Looks ok to me.
I think I left the storage pool as `default` but I don't think naming affects anything.
I just remembered that I set a much bigger storage pool size [200Gb] but only because I have spare space on that VPS and I plan to run a lot more LXC containers.  I think [30gb] should be fine for this app.

**Comment by timconsidine** [comment]
> Thanks! Just wanted to clarify. I will also install it INSIDE the container.

An after-thought : I guess I was also just following the principle of containerisation.  Making sure that nothing else on the box affected the app deployment (or vice versa).

**Comment by bioscopic** [comment]
> > Finished this step: closing bracket complete the command
> 
> Closing the `)` completes the add user command You should then be prompted for the password And get the confirmation Then you should exit the mongo shell Sorry - will update the doc

i figured it out!

**Comment by timconsidine** [comment]
> Getting a failure to start after modifying the conig file: this step. --> uncomment line `#security:`
> 
> --> add line `authorization: enabled` 

It might be formatting.
It's very sensitive
```
security:
  authorization: enabled

#operationProfiling:
```
security in first column
indent 2 spaces then `authorization: enabled`

**Comment by bioscopic** [comment]
> > Getting a failure to start after modifying the conig file: this step. --> uncomment line `#security:`
> > --> add line `authorization: enabled`
> 
> It might be formatting. It's very sensitive
> 
> ```
> security:
>   authorization: enabled
> 
> #operationProfiling:
> ```
> 
> `security:` in first column add a line indent 2 spaces then `authorization: enabled`
> 
> I changed my HOW-TO because it wasn't clear - apologies

That did it! Thanks.

**Comment by bioscopic** [comment]
@timconsidine 
At the nginx reverse proxy step when enabling SSL did you generate a OpenSSL Certificate Signing Request using ED25519? Prefer to generate a ED25519 CSR if possible.  
Im looking at this documentation. https://blog.pinterjann.is/ed25519-certificates.html
Where would the self signed certificate go? Where did you put yours in your build?
I wonder if ED25519 going to work with a browser like Mozilla?

**Comment by timconsidine** [comment]
>  So I need to remove the <db_admin_name> and put what I created between the brackets? same for the <db_password> 

Yes. If username is mongoadmin and you chose "monkeys-dont-fly" as the password, it would be :
  `DB = mongodb://mongoadmin:monkeys-dont-fly@localhost/admin`

> do you leave the leading db_? 

If you mean `DB = mongodb://`, yes leave this

> Just to confirm the pw is the same one for using to secure the mongo in the previous step? 

Yes

> For the BASE_URL = do you put the local IP address here if hosting locally? BASE_URL = https://./ 

The BASE_URL is where your system sits, but it needs to be accessible from Telnyx/Twilio servers.
So normally this would be a domain, e.g. `https://my.smsservice.com/`

> Is it possible to add an internal IP for example something like 192.168.1.xxx? or do you need a public facing IP? Just seeing the reference to a VPS.

I guess it could be an IP address.
But not 192.xxxxx or 10.xxxx or 172.xxxxx
It has to be public ip.
Although I guess if you are running 'at home', you could port forward from your router to your local box (beyond my experience).
Really this needs to be public ip or domain

**Comment by timconsidine** [comment]
> @timconsidine At the nginx reverse proxy step when enabling SSL did you generate a OpenSSL Certificate Signing Request using ED25519? Prefer to generate a ED25519 CSR if possible. Im looking at this documentation. https://blog.pinterjann.is/ed25519-certificates.html 

I normally use Lets Encrypt and its certbot utility
I don't know what is an EDD25519 cert, but it looks like a self-signed certificate.
I don't like self-signed certs as some browsers moan about them.
I guess if you are the only user on the app, and you giver permissions, it's possible.

> Where would the self signed certificate go? 

I don't know !
Probably best to follow a self-signed tutorial

> Where did you put yours in your build? I wonder if ED25519 going to work with a browser like Mozilla?

I use Lets Encrypt and it does it all for you
- generates the cert
- puts it in right directory
- updates your nginx conf file with location

LetsEncrypt is free and lots of good tutorials on how to install `certbot` which is its utility.
Digital Ocean probably have a tutorial.

**Comment by bioscopic** [comment]
>     * The BASE_URL needs to be a public URL (FQDN) as this is used by the VoIP provider to send you the webhook

What is the best provider to get a FQDN for this? One of MB's books talks about namecheap. Is that the way to go? 

>     * If your db is local to the docker, then the db path is localhost or 127.0.0.1
> 
>     * If hosting at home or your own server in a data center, you will need port forwarding (or Static NAT) at your egress firewall from the public IP to the internal local host IP of the box (to receive the webhook at the box)

Hosting at home - This would be a great how to topic to cover having a hardware firewall running pfsense at the edge of the network. Was looking at netgate's documentation on port forwarding. This part of networking is beyond my skill set. How hard would it be to set this up with the VPNs IP assuming your network is behind a VPN?    
> 
> (it get's complicated, I've done it with other deployments, but **every** environment is different. With public free services, at least I know everyone is on the same page). One day I will self host and share all details, until then, I'm learning with you guys/gals. sweat_smile

**Comment by bioscopic** [comment]
@timconsidine Do you have an tutorials on these steps you can point me to?
* set up your DNS to point your domain or subdomain to your VPS
* your container is bridged auto-magically when the container is built and launched
* but that's only fine for outbound traffic : you need inbound traffic (doh!) as well

**Comment by bioscopic** [comment]
> > * set up your DNS to point your domain or subdomain to your VPS
> >   When you set up your DNS to point to your domain did you use two A records one for the subdomain and one for the domain? or did you use an A record for the domain and a CNAME for the www subdomain?
> 
> My main domain already had A record (to another server) The subdomain used for this app : I just used an A record pointing to the public ip address of the server where app is installed
> 

Im getting a Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: redactedforprivacy.com (not a real domain)
  Type:   dns
  Detail: Fetching http://www.redactedforprivacy.com/.well-known/acme-challenge/longstringofcharachersredactedforprivacy: DNS problem: NXDOMAIN looking up A for www.redactedforprivacy.com - check that a DNS record exists for this domain

Any ideas?

> > * your container is bridged auto-magically when the container is built and launched
> > * but that's only fine for outbound traffic : you need inbound traffic (doh!) as well
> >   Did you have to open up a port on your firewall to allow the inbound traffic to the container? Is your Ubuntu server running UFW in your demo/build?
> 
> The "host computer" - meaning the one where the LXC container is running - already had UFW running. I just allowed normal ports, 80, 443, 22
Requesting a certificate for voicevoip.xyz

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: redactedforprivacy.com (not a real domain)
  Type:   connection
  Detail: Fetching http://redactedforprivacy.com/.well-known/acme-challenge/longstringofcharachtersredactedforprivacy: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Got this after modifying the DNS in the hosting provider. Now hung up at the firewall it appears. 

Was your VPS something you self-hosted?
