### ISSUE TITLE
Display a dial pad while in call

### ISSUE THREAD

**Issue by fightforprivacy** [0perationPrivacy/VoIP#86]
**Is your feature request related to a problem? Please describe.**
It isn't anything that is technically broken, however, the lack of an in call dialpad does limit what these numbers can be used for.

**Describe the solution you'd like**
On successful connection, the screen would present a dial pad similar to how Linphone does.

**Describe alternatives you've considered**
Instead of a dialpad, being able to type the number in the number box you dial out from would also work.

**Additional context**
![November - 10 - Idolized](https://user-images.githubusercontent.com/92276223/141233015-fbda8827-7894-4903-a8ca-56c56afdd2e1.png)

**Comment by 0perationPrivacy** [comment]
yes, i added this myself internally in my issues list last week when i faced a problem with punching in numbers 🤪, this is next on my list. Thanks.

**Comment by fightforprivacy** [comment]
I can potentially help out with the coding, if you need to offload something, I would mind helping out.

**Comment by 0perationPrivacy** [comment]
> I can potentially help out with the coding, if you need to offload something, I would mind helping out.

Sure, if you feel there's an area you can contribute to, talk to me about it (so that we're both not working on the same part), create a branch of your fork on your end, test it, create a pull request, I will review it for quality and/or conflict with my programmer and merge it. That's the usual process.
Perfect place to start is working on existing issues or feature requests, they can be re-assigned by me to whomever is working on them.
Thanks.

**Comment by 0perationPrivacy** [comment]
added the feature in v79, but i tested it, the duration of the DTMF tone is quite variable based on latency, not sure if the other side picks it up every time, i have to play around with it using 2 phones and listening in on it. in the next few updates it will be tested and addressed. I'll keep this open till then.

**Comment by 0perationPrivacy** [comment]
dial pad added
